# Generated by Django 5.1.4 on 2025-01-15 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelliweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mentor', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('college', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='desc',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='img',
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('image_url', models.URLField()),
                ('css_id', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='intelliweb.project')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='intelliweb.project')),
            ],
        ),
    ]
